version: "0.2"
services:
  mariadb:
    image: centos/mariadb
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: etherpad
      MYSQL_DATABASE: etherpad
      MYSQL_PASSWORD: etherpad
      MYSQL_USER: etherpad
  etherpad:
    image: centos/etherpad
    ports:
      - "80:9001"
    environment:
      DB_HOST: mariadb
      DB_DBID: etherpad
      DB_PASS: etherpad
      DB_PORT: 3306
      DB_USER: etherpad